"""
Utility script to populate defaults table from local folder.

Usage:
  python -m api.db.populate_defaults              # Insert all genders
  python -m api.db.populate_defaults --female     # Insert only female
  python -m api.db.populate_defaults --male       # Insert only male
  python -m api.db.populate_defaults --other      # Insert only other

Folder structure:
defaults/
├── female/
│   ├── 1.jpg
│   └── ...
├── male/
│   ├── 1.jpg
│   └── ...
└── other/
    ├── 1.jpg
    └── ...

Note: IDs are auto-generated by PostgreSQL (SERIAL), so re-running
this script with new files will append new entries with new IDs.
"""
import sys
import argparse
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from api.db.database import Database
from api.functions.image_functions import ImageFunctions

DEFAULTS_DIR = Path(__file__).parent.parent.parent / "defaults"


def populate_defaults(genders: list):
    """Populate the defaults table with clothing images from local folders."""
    if not DEFAULTS_DIR.exists():
        print(f"Error: Defaults directory not found at {DEFAULTS_DIR}")
        print("Please create the directory structure:")
        print("  defaults/")
        print("  ├── female/")
        print("  ├── male/")
        print("  └── other/")
        return

    image_functions = ImageFunctions()

    # First, read and process all images
    images_to_insert = []

    for gender in genders:
        gender_dir = DEFAULTS_DIR / gender
        if not gender_dir.exists():
            print(f"Skipping {gender} - directory not found at {gender_dir}")
            continue

        image_files = sorted(
            f for f in gender_dir.glob("*")
            if f.suffix.lower() in [".jpg", ".jpeg", ".png", ".webp"]
        )

        if not image_files:
            print(f"No images found in {gender_dir}")
            continue

        print(f"\nProcessing {gender} ({len(image_files)} images):")

        for image_file in image_files:
            try:
                print(f"  Reading {image_file.name}...", end=" ")

                with open(image_file, "rb") as f:
                    image_bytes = f.read()

                preview_bytes = image_functions.create_preview(image_bytes)

                images_to_insert.append({
                    "gender": gender,
                    "image_bytes": image_bytes,
                    "preview_bytes": preview_bytes,
                    "filename": image_file.name
                })
                print("OK")

            except Exception as e:
                print(f"Error: {e}")
                continue

    if not images_to_insert:
        print("\nNo images to insert.")
        return

    # Now insert all processed images into database
    print(f"\nInserting {len(images_to_insert)} images into database...")

    with Database() as db:
        for img_data in images_to_insert:
            try:
                image_id = db.insert_default_image(
                    img_data["gender"],
                    img_data["image_bytes"],
                    img_data["preview_bytes"]
                )
                print(f"  {img_data['gender']}/{img_data['filename']} -> ID: {image_id}")
            except Exception as e:
                print(f"  {img_data['gender']}/{img_data['filename']} -> Error: {e}")

    print("\nDone!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Populate defaults table with clothing images")
    parser.add_argument("--female", action="store_true", help="Insert only female clothing")
    parser.add_argument("--male", action="store_true", help="Insert only male clothing")
    parser.add_argument("--other", action="store_true", help="Insert only other clothing")
    args = parser.parse_args()

    # Determine which genders to process
    genders = []
    if args.female:
        genders.append("female")
    if args.male:
        genders.append("male")
    if args.other:
        genders.append("other")

    # If no specific gender flag, process all
    if not genders:
        genders = ["female", "male", "other"]

    populate_defaults(genders)
